name: subly
description: SubTrack - Subscription management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  fl_chart: ^0.70.2
  uuid: ^4.5.1
  lottie: ^3.3.1
  image_cropper: ^8.0.2
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.4.0
  timezone: ^0.10.0
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_messaging: ^15.2.4
  unity_ads_plugin:
    path: packages/unity_ads_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/icons/bottom_nave_home.png
    - assets/icons/bottom_nav_add.png
    - assets/icons/bottom_nav_calander.png
    - assets/icons/bottom_nav_mage_chart.png
    - assets/icons/bottom_nav_settingpng.png
    - assets/icons/
    - assets/images/splash_logo.png
    - assets/animations/notfound.json
